### PR TITLE
Bring back block class now as eblock class

### PR DESCRIPTION
**Pull request by markhdavid**
This is a continuation or spinoff of PF #145 -- it had to be rebased with dev.

### CODE REVIEW

**Comment by easye** [comment]
Repeating myself on points from the previous review (#145 ):

1.  Mark `src/blockchain.lisp` as not the current block definition (move to a subdirectory called "brooks" or "prototype"?). Certainly, the ASDF definition in emotiq.asd for `emotiq/blockchain` can bre renamed.  Otherwise the not-used-at-all code in `src/blockchain.lisp` is going to cause a lot of confusion for reviewers of our codebase.

2.  Add `:accessor` or `:reader` as well as `:initarg` to the eblock `defclass` for slots which lack them to bring the code in line with the current conventions followed in the rest of the source tree. 

Neither of these points are a blocker to approving this request, but they should be noted for future consideration.

**Review by easye — APPROVED** [review]
See previous comment for non-blocking suggestions to improve the codebase based on this commit.

**Comment by markhdavid** [comment]
I have to rebase and do another PR on a new branch, closing this PR. Will update with successor PR. New branch 155932861-block-class-9may18-again-rebased-with-dev

**Comment by markhdavid** [comment]
Successor PR = Bring back block class now as eblock class #152

https://github.com/emotiq/emotiq/pull/152

**Pull request closed without merging**
