### PR TITLE
latest changes to support LW Linux

### PR DESCRIPTION
**Pull request by dbmcclain**

### CODE REVIEW

**Comment by markhdavid** [comment]
REJECTED.
We don't base off of "master' branch.
David, please redo the PR with "dev" as the base.

**Review by markhdavid — COMMENTED** [review]
This is rejected because it's based off the wrong branch, master, whereas it should be based off  branch dev. It's also too big, which derives from it being based off of master and also the fact that so many disparate changes were rolled in. This is superseded by a still too big but relatively manageable PR "MHD's Proposed PR for DBM #18", based off dev. This PR has to die soon. Sorry.

**Review by dbmcclain — COMMENTED** [review]
looks okay

**Review by dbmcclain — COMMENTED** [review]
please kill this PR. I think it is blocking me from interacting with dbm repo

**Review by markhdavid — COMMENTED** [review]
This was a long tortured PR. It had a fatal flaw being based off the wrong branch, master. Should have been dev. Most of its good efforts ended up on the PR based on dev. Some of the weird oddities we'll be happy to forget. Good riddance! PR has been closed.

**Pull request closed without merging**
