### PR TITLE
Integrate relevant changes for socket-actors

### PR DESCRIPTION
**Pull request by lukego**
This branch merges several other related branches together:

- `dev` for the latest mainline changes;
- `socket-actors` for Gossip-over-TCP support;
- `config-mte` for updates to the configuration file format (also with one minor fix added.)

These changes do seem worth merging together so I proposed that after review we either:

- Merge this branch upstream to `dev` (implicitly landing `socket-actors` and `config-mte`); or
- Merge this branch onto `socket-actors` if more changes are needed before upstreaming.

I have integrated the changes together using `git merge --no-ff` to capture maximum information in the Git history but I'm happy to rebase/squash/etc if preferred.

### CODE REVIEW

**Review by easye — COMMENTED** [review]
Really need @svspire to weigh on the best merge strategy before reviewing this in any meaningful manner.

**Comment by svspire** [comment]
config-mte needs to be omitted from this. It's completely obsolete.

**Comment by svspire** [comment]
Please merge branch svs7 into this, rather than config-mte.

**Comment by easye** [comment]
@lukego Probably a good idea to just close this pull request.  Yesterday, we merged the latest version of the TCP networking code as <https://github.com/emotiq/emotiq/pull/159> which includes the newer configuration mechanism.

**Comment by lukego** [comment]
Superseded as @easye points out!

**Pull request closed without merging**
