### PR TITLE
remove debugging code from last commit

### PR DESCRIPTION
**Pull request by markhdavid**

### CODE REVIEW

**Comment by markhdavid** [comment]
@guitarvydas thanks for noticing this and bringing to my attention

**Review by guitarvydas — APPROVED** [review]
You "assigned" me (whatever that means) then I added myself as a reviewer.

**Comment by markhdavid** [comment]
Oh, I don't really remember assignment vs. reviewer. Will have to look up.  It just came up as more easy from a button pushing perspective probably so I went for it. :)

**Comment by markhdavid** [comment]
oh sorry did notice @echupriyanov had explicitly restored the branch!

**Pull request merged**
