### PR TITLE
Added one line in BLOCK-FINISH handler to call for new regular electi…

### PR DESCRIPTION
**Pull request by dbmcclain**
…on. The Leader calls this unless a problem has arisen. In case of problems, system will timeout on emergency call for election and resync just like at genesis.

### CODE REVIEW

**Comment by dbmcclain** [comment]
Looks like the CI pipeline is failing because, with recurrent elections, the tests never terminate...

**Comment by easye** [comment]
> with recurrent elections, the tests never terminate...

Hmmm. Not sure of the right way to fix that.  

Can we add a parameter to `run-new-tx` to control whether elections are called again somehow?

Since we probably want the default to be to have elections, we need a way to turn elections off I am supposing.

**Comment by dbmcclain** [comment]
one more special var I guess

let me know how you want to proceed. There are an accumulating number of special switches (vars) peppered over the source code already. At some point this will get out of hand. Needs a good organizing principle instead of ad-hoc, along with some foresight into setup and config

**Comment by easye** [comment]
>There are an accumulating number of special switches (vars) peppered over the source code already. At some point this will get out of hand. Needs a good organizing principle instead of ad-hoc, along with some foresight into setup and config

Agreed. My naive first instinct would  be to centralize such things in `emotiq/config`

**Review by easye — CHANGES_REQUESTED** [review]
Not merging until we figure how to keep the tests working.

**Pull request closed without merging**
