### PR TITLE
158153939 configure run minimal distributed

### PR DESCRIPTION
**Pull request by easye**
Implement two REST methods for launching and introspecting the simulator:

To start the simulator:

    POST http://localhost:3140/simulator/

To introspect the state of the simulator

    GET http://localhost:3140/node/

The API may be interactively browsed at http://localhost:3140/  

@guitarvydas I was not able to use `emotiq/ate` due to circular ASDF dependencies, so I copied what I needed into `src/network/rest/simulator-0.0.1.lisp`.  This is a hack, and I need to fix, but I wanted to get a basic node out for @echupriyanov to be able to script, and this code implements that bare minimum.

### CODE REVIEW

**Comment by easye** [comment]
@echupriyanov @guitarvydas Please review updated pull request.

With <https://github.com/emotiq/emotiq/pull/251/commits/a8abb08771f36993bd47aee082d8d2db04e24029> should the REST API for the simulator to be useful for Eugene.  

With this commit, 
```
curl --request post http://localhost:3140/simulator
```
asynchronously invokes the simulator, returning the URI of the resource to poll for output from the simulation.  

Independently of the simulator, one may ensure that the PBC libraries have been initialized correctly by querying the existence of a wallet via 

``` 
curl http://localhost:3140/wallet/
```

**Review by guitarvydas — COMMENTED** [review]
Starting for the first time, clicking on "Output from simulator" gives an error

screenshot 2018-06-26 12 07 32

**Comment by echupriyanov** [comment]
I'm getting following:
```
emotiq@tchu-emq-02:~$ curl http://localhost:3140/simulator/0

Tx 0 created/genesis, now broadcasting.
  TxID: 4af388ae8739f974e72dd38b53f537c2414997c560df8fc683eb628e28febf29
    input outpoint: index = -1/TxID = 0000000000000000000000000000000000000000000000000000000000000000
    outputs:
      [0] amt = 100000000000000000 (out to) addr = z2Yz1mFPwyvJWfqjrQ52GzVktUJJN9ciah

Tx 1 created/signed by genesis (z2Yz1mFPwyvJWfqjrQ52GzVktUJJN9ciah), now broadcasting.
  TxID: 1991c27dcb93beafd1272a6b6007804f1a08ec1ceb7c0b79813749885a0a2293
    input outpoint: index = 0/TxID = 4af388ae8739f974e72dd38b53f537c2414997c560df8fc683eb628e28febf29
    outputs:
      [0] amt = 890 (out to) addr = z2QKxCenP46TNncbs9S2PUY3nhaeN1s1up
      [1] amt = 99999999999999100 (out to) addr = z2Yz1mFPwyvJWfqjrQ52GzVktUJJN9ciah

Tx 2 created/signed by user-1 (z2QKxCenP46TNncbs9S2PUY3nhaeN1s1up), now broadcasting.
  TxID: b0b7b7f80bae89510865bd1b2973e3daf93550ae7ecbb6d2dea1948925c6ec90
    input outpoint: index = 0/TxID = 1991c27dcb93beafd1272a6b6007804f1a08ec1ceb7c0b79813749885a0a2293
    outputs:
      [0] amt = 500 (out to) addr = z6E1656FtNMBFSEt99bviPt6psE4th2Eoo
      [1] amt = 380 (out to) addr = z2QKxCenP46TNncbs9S2PUY3nhaeN1s1up

Tx 3 created/signed by user-2 (z6E1656FtNMBFSEt99bviPt6psE4th2Eoo), now broadcasting.
  TxID: d8ee63af06fedee0c41a6c2529fa88561b9c299655af0a422152ca6933f80c89
    input outpoint: index = 0/TxID = b0b7b7f80bae89510865bd1b2973e3daf93550ae7ecbb6d2dea1948925c6ec90
    outputs:
      [0] amt = 350 (out to) addr = z61ugfFsNUvESSqpPdddhN3rCE7YrrsaRQ
      [1] amt = 140 (out to) addr = z6E1656FtNMBFSEt99bviPt6psE4th2Eoo

Tx 4 created/signed by user-2 (z6E1656FtNMBFSEt99bviPt6psE4th2Eoo) [attempt to double-spend (same TxID)], now broadcasting.
Tx 5 created/signed by user-2 (z6E1656FtNMBFSEt99bviPt6psE4th2Eoo) [attempt to double-spend (diff TxID)], now broadcasting.
> Error: Invalid program: INITIALLY is an unknown keyword in FOR or AS clause in LOOP.
>        Current LOOP context: AS TIME-THROUGH INITIALLY (FORMAT T "~%~a~d" MESSAGE N) WHEN.
> While executing: COSI/PROOFS/NEWTX:WAIT-FOR-TX-COUNT, in process Anonymous thread(13).
```

**Comment by guitarvydas** [comment]
@echupriyanov I'm clicking "Output from simulator" before I click "create" (a simulator).  This makes sense (since I haven't run the simulator) and should be easy to fix.  I simply wanted to "note" this before I start using the interface the way it is intended (and before I forget what happened the first time).

**Comment by easye** [comment]
Closed in favor of <https://github.com/emotiq/emotiq/pull/262>

**Pull request closed without merging**
