### PR TITLE
Pt2 158153939 configure run minimal distributed

### PR DESCRIPTION
**Pull request by guitarvydas**
This version should supercede pt-158153939-configure-run-minimal-distributed and 158153939-configure-run-minimal-distributed (PR259 & 251).  This version pt2-...) has one more commit - a merge with dev as evidenced by the line `https://github.com/emotiq/emotiq/blob/dev/src/Cosi-BLS/cosi-construction.lisp#L128`

### CODE REVIEW

**Comment by guitarvydas** [comment]
I've forgotten to add [158153939] to the commit comment.

**Comment by easye** [comment]
Hmmm, all the information from simulator going to `emotiq:note` is no longer available via <http://localhost:3140/simulator/0>.  

All I see is 
```
..............Done.
```
@guitarvydas Is this what you intend?  Why not concatenate the messages passed to `emotiq:note` as it was before?

**Review by easye — CHANGES_REQUESTED** [review]
It doesn't seem that this helps improve the diagnostics of what the simulator is doing via REST.  

I expected that the state tracker would have additional information attached to it, but it seems unchanged.

Could you please offer a little guidance on the completeness of this pull request?

**Comment by guitarvydas** [comment]
What is seen is correct, but there is more add-on work, discussed in the new Twist thread.  I will re-open a PR later.

**Pull request closed without merging**
