### PR TITLE
Ensure that EMOTIQ-TEST passes its suite

### PR DESCRIPTION
**Pull request by easye**
Conditionalize testing of normalized strings under CCL for now, fix
later.

Addresses <https://github.com/emotiq/emotiq/issues/314>.

### CODE REVIEW

**Review by echupriyanov — CHANGES_REQUESTED** [review]
Now we have:
```lisp
The following function is undefined:
EMOTIQ/TRACKER:TRACK which is referenced by (METHOD COSI-SIMGEN:NODE-DISPATCHER ((EQL :BLOCK-FINISHED))), (METHOD COSI-SIMGEN:NODE-DISPATCHER ((EQL :COSI-SIGN-COMMIT))), (METHOD COSI-SIMGEN:NODE-DISPATCHER ((EQL :COSI-SIGN-PREPARE))), (METHOD COSI-SIMGEN:NODE-DISPATCHER ((EQL :MAKE-BLOCK))), (METHOD COSI-SIMGEN:NODE-DISPATCHER ((EQL :RESET))), (METHOD COSI-SIMGEN:NODE-DISPATCHER ((EQL :BECOME-WITNESS))), and (METHOD COSI-SIMGEN:NODE-DISPATCHER ((EQL :BECOME-LEADER)))
```
in `:COSI-BLS-TEST`

**Comment by easye** [comment]
@dbmcclain Could you fix the failing test in `cosi-bls-test`, namely `cloaked-transaction-consistency`? 

This would help establish a "green" baseline in `dev`, which is kinda a priority with `mgmt`

**Comment by dbmcclain** [comment]
I just pulled in dev branch. Looked for test. Found it. But it uses my old transaction system. So fix will entail digging into Mark D’s new transactions, learn how to form a cloaked transaction, and substutute that for the creation code currently in the test. Will take some time to dig into Mark’s code.

- DM

**Comment by easye** [comment]
Thanks.

Can you work off of the test-restore-green branch associated with <https://github.com/emotiq/emotiq/pull/315> instead of dbm?

**Comment by dbmcclain** [comment]
got test-restore-green branch to begin work

**Comment by easye** [comment]
@echupriyanov `cosi-test` and `cosi-bls-test` now pass. Please review when you get a chance.

**Review by echupriyanov — APPROVED** [review]

**Pull request merged**
