### PR TITLE
158634075 generate gossip config port

### PR DESCRIPTION
**Pull request by easye**
Distinguish generated testnet configuration by port number.

### CODE REVIEW

**Review by echupriyanov — APPROVED** [review]
Thanks!

**Comment by svspire** [comment]
Colons are illegal characters in filenames in MacOS. Is this only for Linux?

**Comment by echupriyanov** [comment]
Why? They work ok in macOS

**Comment by svspire** [comment]
Got to the Finder, click on a file, hit RETURN, and attempt to rename a file by adding a ":" character. It will fail.

**Comment by svspire** [comment]
Historically -- prior to OSX -- MacOS used the colon as a directory separator. They have kept that ability for backwards compatibility. If you force a colon character into a filename programmatically, it will be internally escaped, which means the filename may or may not be portable to other file systems.

**Pull request merged**
