### PR TITLE
 Eliminate conflicting import of CONVERT-BYTES-TO-INT from :EDWARDS-E…

### PR DESCRIPTION
**Pull request by markhdavid**
…CC in favor :ECC-CRYPTO-B571.

 In fact, both symbols stem from self-same source file: src/Crypto/utilities.lisp
 This is really bug in any Common Lisp, but only seems to have manifested itself so far in CCL.

### CODE REVIEW

**Review by svspire — APPROVED** [review]

**Comment by markhdavid** [comment]
I added an additional change: disable in-package of non-existent package cosi-test, which was crashing CCL CI

*** SHANNON *** can you approve the 2nd change, disabling the in-package for a bad package

**Review by easye — COMMENTED** [review]
Fixed running an empty cosi-test via 
 
https://github.com/emotiq/emotiq/pull/14/commits/a1d71bc3ec3d6576bb844bf88017e202d9d8b44c

Tests for `cosi` now invoke for me under `ccl`

**Review by easye — COMMENTED** [review]
`cosi` does not compile for me under `lwpro-7.1` because of missing references to the `rch` package

This is not specific to this merge request, but noting here.

```
;;; Compiling file /Users/evenson/work/emotiq/src/Crypto/primes.lisp ...
;;; Safety = 3, Speed = 1, Space = 1, Float = 1, Interruptible = 1
;;; Compilation speed = 1, Debug = 2, Fixnum safety = 3
;;; Source level debugging is on
;;; Source file recording is  on
;;; Cross referencing is on
; (TOP-LEVEL-FORM 0)
; (TOP-LEVEL-FORM 1)
; (TOP-LEVEL-FORM 2)
; PRIMES::MT-RANDOM
; PRIMES:RANDOM-BETWEEN
; (TOP-LEVEL-FORM 5)
; PRIMES::|2^|
; PRIMES::|2^|
; PRIMES:DIVIDES?
; PRIMES:DIVIDES?
; PRIMES:ADD-MOD
; PRIMES:ADD-MOD
; PRIMES:SUB-MOD
; PRIMES:SUB-MOD
; PRIMES:MULT-MOD
; PRIMES:MULT-MOD
; PRIMES:INV-MOD
; PRIMES:DIV-MOD
; PRIMES:DIV-MOD
; PRIMES:EXPT-MOD
; (DEFVAR PRIMES::*PRIMES*)
; PRIMES:MAKE-PRIME
; PRIMES::FACTOR-OUT
; PRIMES::PERFECT-SQUARE?
; PRIMES::JACOBI-SYMBOL
; PRIMES::PROBABILISTIC-LUCAS-TEST
; PRIMES::MAKE-STRONG-MILLER-RABIN-LIAR-TEST
; PRIMES::PROBABILISTIC-MILLER-RABIN-PRIME?
; PRIMES::DETERMINISTIC-MILLER-RABIN-PRIME?
; PRIMES::MILLER-RABIN-PRIME?
; PRIMES:IS-PRIME?
; PRIMES:EXTENDED-GCD
; PRIMES:COMPUTE-MODULO-INVERSE
; PRIMES::TEST-PRIMITIVE-ROOT
; PRIMES::LUCAS-LEHMER-TEST
; PRIMES:PROVABLY-PRIME?
; PRIMES:FACTORS-OF
; PRIMES::TOTIENT
;;;*** Warning in PRIMES:GENERATE-STRONG-PRIME: Eliminating a test of a variable with a declared type : PRIMES::NLEVELS [type FIXNUM]
;;;*** Warning in PRIMES:GENERATE-STRONG-PRIME: Eliminating a test of a variable with a declared type : PRIMES::NLEVELS [type FIXNUM]
;;;*** Warning in PRIMES:GENERATE-STRONG-PRIME: Eliminating a test of a variable with a declared type : PRIMES::NLEVELS [type FIXNUM]
; PRIMES:GENERATE-STRONG-PRIME
; PRIMES::COMPUTE-DIFFIE-HELLMAN
; PRIMES::COMPUTE-RSA-D&E
; PRIMES:GENERATE-RSA-BASE
; (DEFVAR PRIMES::*DAVES-N-KEY*)
; (DEFVAR PRIMES::*DAVES-E-KEY*)
; (DEFVAR PRIMES::*DAVES-D-KEY*)
; (DEFVAR PRIMES::*DAVES-P-PRIME*)
; (DEFVAR PRIMES::*DAVES-Q-PRIME*)
; PRIMES::GENERATE-SAFE-PRIME

**++++ Error between functions:
  Reader cannot find package RCH.

**++++ Error between functions:
  Reader cannot find package RCH.

**++++ Error between functions:
  Reader cannot find package RCH.

**++++ Error between functions:
  Reader cannot find package RCH.

**++++ Error between functions:
  Reader cannot find package RCH.
; PRIMES::PAR-GEN-SAFE-PRIMES
; PRIMES::SHOW-GROUP
; PRIMES::SHOW-GENS
; PRIMES::CONVERT-BYTES-TO-INTEGER
; PRIMES::CONVERT-INTEGER-TO-VECTOR
; (METHOD PRIMES::INTEGER-OF (INTEGER))
; (METHOD PRIMES::INTEGER-OF (VECTOR))
; (METHOD PRIMES::INTEGER-OF (UUID:UUID))
; (METHOD PRIMES::INTEGER-OF (STRING))
; (METHOD PRIMES::VECTOR-OF (VECTOR))
; (DEFTYPE PRIMES::VECTOR-UB8)
; PRIMES::STRING-TO-VECTOR
; (METHOD PRIMES::VECTOR-OF (STRING))
; (METHOD PRIMES::VECTOR-OF (UUID:UUID))
; (METHOD PRIMES::VECTOR-OF (INTEGER))
; PRIMES::MAKE-NBIT-PRIME
; PRIMES::GEN-DSA-PRIMES
; PRIMES::MAKE-2KP+1-PRIME

**++++ Error between functions:
  Reader cannot find package RCH.

**++++ Error between functions:
  Reader cannot find package RCH.

**++++ Error between functions:
  Reader cannot find package RCH.

**++++ Error between functions:
  Reader cannot find package RCH.

**++++ Error between functions:
  Reader cannot find package RCH.

**++++ Error between functions:
  Reader cannot find package RCH.
; PRIMES::PAR-MAKE-2KP+1-PRIME
; PRIMES::MAKE-2Q+1-PRIME
; (TOP-LEVEL-FORM 64)
; PRIMES::SQR
; PRIMES::SQR
; PRIMES::BIG-LOG
; PRIMES::BIG-LOG
; PRIMES::PDENS
; PRIMES::PDENS

**++++ Error between functions:
  Reader cannot find package RCH.

**++++ Error between functions:
  Reader cannot find package RCH.

**++++ Error between functions:
  Reader cannot find package RCH.

**++++ Error between functions:
  Reader cannot find package RCH.

**++++ Error between functions:
  Reader cannot find package RCH.

**++++ Error between functions:
  Reader cannot find package RCH.

**++++ Error between functions:
  Reader cannot find package RCH.

**++++ Error between functions:
  Reader cannot find package RCH.

**++++ Error between functions:
  Reader cannot find package RCH.
; PRIMES::FIND-PRIMITIVE-ROOT
; PRIMES::COLLECT-SAFE-PRIMES
; PRIMES:DECOMPOSE
; PRIMES::EVENS
; PRIMES::ODDS
; PRIMES::FFT
; PRIMES::IFFT
; PRIMES::FIND-FFT-PRIME
; PRIMES::SHUFFLE
; PRIMES::CHKROOT
; PRIMES::TRY-FIND-FIELD-FOR-FFT
; PRIMES::FIND-FIELD-FOR-FFT
; PRIMES::MAKE-LAGRANGE-INTERPOLATOR
; PRIMES::SOLVE-LAGRANGE
;; Processing Cross Reference Information
; *** 20 errors detected, no fasl file produced.
```

**Comment by easye** [comment]
I hacked the conditionals to get `cosi` to compile for me under `lwpro-7.1-macos` in https://github.com/emotiq/emotiq/tree/mte-cosi-tweaks

**Comment by dbmcclain** [comment]
Seems this error keeps growing back after every time I chop its head off... The correct import is from :ECC-CRYPTO-B571. It is actually the same symbol beneath both imports, and deemed "not an error, by LW Martin Simmons". It would be an error if it referred to different symbols in each import, but in this case it points to the same underlying symbol. Language of the CL Spec is ambiguous, and LW has chosen to interpret to mean "disjoint in the same declarative form, not extending to the outer enclosing form".

**Comment by markhdavid** [comment]
Well, the last changes were discussed in twist. First, there were a few whack-a-mole type changes, and then we got done with :cosi. Then in trying to finish :cosi-test, we noticed a problem: to sum up: when Mark E applied several of David's changes overnight (Pacific time), there were some merge conflicts, but he must have not noticed that, since he evidently committed a source file with the merge conflict meta characters (<<<, ===, >>>). I reverted those changes, and reapplied them and resolved the conflicts. The :cosi-test now works, and David agrees with the merge choices I made. The CI is still not happy, but I think it's down to confusion around return status from the Lisp processj (is the return status suppose to be "-1" or "0" or what?), and possibly failing a test suite because there simply are no tests. For example, does (lisp-unit:run-tests :all :cosi-test) return a bad result, and is that causing the CI to report failure? And if so, is it because there simply are no tests defined yet? I certainly do not wish to spend further time spinning wheels pondering this now, and I will not. Leaving that for Mark E, who introduced that form into the CI. For now, going to merge the pull request. and declare victory.  

*** PLEASE NOBODY PUT ANYTHING ON THIS BRANCH cosi-tweaks NOW. We are done with it. OR TALK TO ME FIRST***

**Pull request merged**
