### PR TITLE
157484804 create websocket interface

### PR DESCRIPTION
**Pull request by easye**

### CODE REVIEW

**Comment by easye** [comment]
@guitarvydas and @echupriyanov 

This branch starts gossip, websockets, and REST.  The problem is that if a gossip configuration doesn't exist, the code will execute.  

It would be helpful if both of you could help me figure out what the right thing to do would be. 

If we can get this merged, Eugene can then query for wallet creation via a simple REST request to the running daemon.  

We need to figure out how to shutdown the node.

**Review by guitarvydas — COMMENTED** [review]
I still see
```
[package hunchensocket]..
.........................
[package websocket/wallet].

The following function is undefined:
UNSIGNED-BYTE which is referenced by EMOTIQ/WALLET::ENCRYPT-WALLET

(:EMOTIQ/STARTUP)
```
hmmm.  see http://clhs.lisp.se/Body/t_unsgn_.htm.  Lispworks.

**Comment by easye** [comment]
@guitarvydas @markhdavid  Please review the 15-FRI-2018 updates.  

@echupriyanov This is the version of `emotiq` that you can communicate via REST/websockets to query/control the node for testing and deployment.

**Review by guitarvydas — APPROVED** [review]
I didn't have time to browse the websocket stuff.

**Pull request merged**
