### PR TITLE
PBC Crypto, BLS MultiSignatures, PBC Lynn Libs, GNU MP Libs

### PR DESCRIPTION
**Pull request by dbmcclain**

### CODE REVIEW

**Comment by easye** [comment]
Missing the `cosi/base58.lisp` file.

**Review by easye — CHANGES_REQUESTED** [review]
This branch does not compile as it is missing `src/Cosi/base58.lisp`.  Please ensure that the `cosi` system can be compiled by adding the missing artifacts to this branch, and request additional review.

Not too happy about including the source tarballs for the C code directly in the tree, but will accept that for the time being until we come up with a recommendation on how to include such dependencies.  Such source tarballs add considerable bloat to the repository history.  Again not sure that right way forward.

Additionally, this merge request contains at least three contributions that would better be factored into separate pull requests:

1.  Moving Okeanos out of the `src/` hierarchy

2. Getting the PBC native libraries working 

3.  Work on the pure-CL base58 encoding in `core-crypto`

Let's just work on getting `cosi` to compile rather than trying to split this merge up into logical grouping, especially as I don't currently have a concrete recommendation on how to deal with native libraries yet, so would rather examine your work on `dev` to make suggestions.

**Comment by dbmcclain** [comment]
a copy of base58.lisp has been placed back into the old Cosi folder

**Comment by easye** [comment]
@dbmcclain Compile completes with the following warnings:
```
cd /Users/evenson/quicklisp/dists/quicklisp/software/external-program-20160825-git/src/
3 compiler notes:

/Users/evenson/work/emotiq/src/Cosi/cosi-sockets.lisp:82:1:
  warning: Undefined function ASSOCIATE-AID-WITH-ACTOR

/Users/evenson/work/emotiq/src/Cosi/cosi-sockets.lisp:98:1:
  warning: Undefined function UNREGISTER-AID

/Users/evenson/work/emotiq/src/Cosi/cosi-sockets.lisp:196:1:
  warning: Undefined function LOOKUP-ACTOR-FOR-AID

```

Thanks for the merge!

**Comment by dbmcclain** [comment]
The problem area is found in cosi-sockets.lisp, after DEFMONITOR. My system expands the DEFMONITOR macro to the following:

```(LET* ((#:LOCK5012 (MP:MAKE-LOCK))
       (#:LAM5011
        (LAMBDA (&REST #:ARGS5010)
          (MP:WITH-LOCK (#:LOCK5012)
            (DLAM:DCASE #:ARGS5010
                        (ASSOCIATE-AID-WITH-ACTOR (AID ACTOR) (SETF (GETHASH AID *AID-TBL*) ACTOR))
                        (LOOKUP-ACTOR-FOR-AID (AID) (GETHASH AID *AID-TBL*))
                        (UNREGISTER-AID (AID) (REMHASH AID *AID-TBL*)))))))
  (DEFUN ASSOCIATE-AID-WITH-ACTOR (&REST #:FARGS5009) (APPLY #:LAM5011 'ASSOCIATE-AID-WITH-ACTOR #:FARGS5009))
  (DEFUN LOOKUP-ACTOR-FOR-AID (&REST #:FARGS5009) (APPLY #:LAM5011 'LOOKUP-ACTOR-FOR-AID #:FARGS5009))
  (DEFUN UNREGISTER-AID (&REST #:FARGS5009) (APPLY #:LAM5011 'UNREGISTER-AID #:FARGS5009)))```

So, not undefined functions. Something is amiss in your version of DEFMONITOR, from useful-macros

**Pull request closed without merging**
