### PR TITLE
Gossip

### PR DESCRIPTION
**Pull request by svspire**
Handles replies.
Tests present and working.

### CODE REVIEW

**Comment by easye** [comment]
The tests don't execute
```(asdf:test-system :gossip-tests)```
fails with
```Package GOSSIP-TEST not found```

**Comment by easye** [comment]
Additionally, it please add an `:in-order-to` clause in the system that is exercised in the tests as in

https://github.com/emotiq/emotiq/blob/dev/src/emotiq.asd#L11

**Review by easye — CHANGES_REQUESTED** [review]
Please fix it so that the tests can be run.

**Comment by svspire** [comment]
Try pulling my latest push instead. I think I fixed the typo.
As for :in-order-to, I have no idea what that clause or :perform is for, and the ASDF docs are impenetrable to me. So please feel free to correct those yourself.

**Comment by easye** [comment]
@svspire 

The `:in-order-to` clause at https://github.com/emotiq/emotiq/blob/dev/src/emotiq.asd#L11 tells that in order to perform the tests on the `emotiq` system to run test-op on the `emotiq-test` system.

You already have a `:perform` clause in https://github.com/emotiq/emotiq/blob/gossip/src/gossip/gossip-tests.asd#L10, which is how you are getting 

```(asdf:test-system :gossip-test)``` 

to run.

If you were to add the `:in-order-to` clause in `gossip.asd`, you would be able to invoke these tests via

```(asdf:test-system :gossip```

**Review by easye — APPROVED** [review]
At least the tests can be invoked now, if not quite in the way I requested.

**Pull request merged**
