### PR TITLE
Gossip rebased on dev b40ef75

### PR DESCRIPTION
**Pull request by markhdavid**
I checked out gossip and rebased it onto dev (with latest commit b40ef75) and created the branch gossip-rebased-on-dev-b40ef75. So that's what this pull request is. It has a lot less diffs vs base dev.

Shannon, can you check this out, and see if this has the changes you need, and if you lost anything?

The other branch seemed to have way too much junk in it.  And doing a rebase got rebase / merge "errors".  I closed the other pull request. (It's not gone, just has status closed.)

### CODE REVIEW

**Comment by markhdavid** [comment]
Shannon's note about this in Twist was:

> Just issued a pull request for gossip. It's in a subdirectory of emotiq/src. See the readme.txt to test. You'll need to install graphviz if you want to visualize the network, but this is not necessary for testing.

I tried running it in Lispworks on my Mac in both the original submitted branch (gossip) and my new derived rebased branch (gossip-rebased-on-dev-b40ef75) that this pull request is for, and in both cases, I did not really get the expected results at the end, as they're described. 

Here are the last 4 lines I got last time I ran the last command the readme tells you to run:

> 15                (:IGNORE "node8" "sol12" :FROM "node7" ...)
> 16                (:WAITING "node9" "sol12" (10 8))
> 17                (:IGNORE "node5" "sol12" :FROM "node8" ...)
> 18                (:IGNORE "node9" "sol12" :FROM "node8" ...) ........ (:dm or :dr for more)

Readme says it should different, saying:

> ;; You should see a final entry like
> (:FINALREPLY "node1" "sol12" (2 9 8 3 7 ...)) ........ 
> Where the list beginning "(2 9 8 3 7 ...)" should contain
> all (or most) of the nodes in the graph.

**Comment by markhdavid** [comment]
Also, as Joel commented, I don't really want to have an external key-value database in a separate repo. Joel said, why not have it inside our repo.  I'd have to agree.  I'd just stick it in a module and not even make it a system of it.  I might even flet it just as an overreaction to all the over indirection I sometimes encounter. :)

**Comment by svspire** [comment]
> Here are the last 4 lines I got last time I ran the last command the readme tells you to run:

> 15 (:IGNORE "node8" "sol12" :FROM "node7" ...)
> 16 (:WAITING "node9" "sol12" (10 8))
> 17 (:IGNORE "node5" "sol12" :FROM "node8" ...)
> 18 (:IGNORE "node9" "sol12" :FROM "node8" ...) ........ (:dm or :dr for more)

For some reason, (inspect *log*) in LW refuses to show you the entire log, and you have to type :dm or :dr (which I assume mean "display more" and "display remainder") to see the entire log. I wish there were a way to launch the GUI inspector from the command line -- there probably is, but I haven't figured it out yet. As things stand, the LW GUI inspector is useless to me.

**Review by svspire — APPROVED** [review]

**Comment by markhdavid** [comment]
OK, weird, but yes, I typed several times
> :dm

then saw final line

>58      (:FINALREPLY "node1" "sol12" (10 9 8 2 6 ...)) ........ (:dm or :dr for more) @

**Comment by markhdavid** [comment]
Shannon approved this. I will merge this presently

**Comment by svspire** [comment]
" (:dm or :dr for more)" is coming from LW; not from me. Whenever you see that, there's more output available (I think).

**Comment by markhdavid** [comment]
OK, it compiles after last update on CCL. (Gets past the package read error.)

**Pull request merged**
