### PR TITLE
Extend `demo-network` to run more than 3 nodes

### LINKED ISSUE #376: Extend `demo-network` to run more than 3 nodes on localhost

### PR DESCRIPTION
**Pull request by echupriyanov**
Resolves #376

### CODE REVIEW

**Comment by echupriyanov** [comment]
@easye I've updated PR to match current `dev`, please, review at your convenience

**Comment by echupriyanov** [comment]
@dbmcclain There is `demo-network/README.md` file describing how to run `demo-network`
It works fine with CCL. For LispWorks I haven't figured out how to start command-line LispWorks and make it run some code from .lisp file and stay in REPL (like ccl does with `ccl -l <some-lisp-file>.lisp`, so I just start with infinite loop in listener

**Comment by dbmcclain** [comment]
testing out this branch right now.
When I do (ql:quickload :emotiq/startup) from a virgin LWM system, I get the following messages:

The following functions are undefined:
ROUTE.WALLET/0/0/1::NAME which is referenced by ROUTE.WALLET/0/0/1::%GET-TRANSACTION and ROUTE.WALLET/0/0/1::%SUBMIT-TRANSACTION/POST
ROUTE.WALLET/0/0/1::WITH-WALLET-NAMED which is referenced by ROUTE.WALLET/0/0/1::%GET-TRANSACTION and ROUTE.WALLET/0/0/1::%SUBMIT-TRANSACTION/POST

Perhaps that is okay, I don't know. That might not even be the correct way to start up this branch. I do see that the CI approved this merge. I will review your docs to be sure. When I do same from CCL, I get no messages showing at the end of the load.

**Comment by dbmcclain** [comment]
Doing a recursive grep on Emotiq/, I do see that WITH-WALLET-NAMED is being used in two places in wallet-0.0.1.lisp. 

From the sounds of it, your proposed changes have nothing to do with wallet code. So I am approving and merging this PR now. Branch dev already had problems before, and so this merge wouldn't seem to change that situation.

**Review by dbmcclain — APPROVED** [review]
approved

**Comment by echupriyanov** [comment]
@dbmcclain thanks!

**Comment by easye** [comment]
@dbmcclain 

> The following functions are undefined:
ROUTE.WALLET/0/0/1::NAME which is referenced by ROUTE.WALLET/0/0/1::%GET-TRANSACTION and ROUTE.WALLET/0/0/1::%SUBMIT-TRANSACTION/POST
ROUTE.WALLET/0/0/1::WITH-WALLET-NAMED which is referenced by ROUTE.WALLET/0/0/1::%GET-TRANSACTION and ROUTE.WALLET/0/0/1::%SUBMIT-TRANSACTION/POST

> Perhaps that is okay, I don't know. 

These undefined references have been fixed in <https://github.com/emotiq/emotiq/tree/mvp-websocket-20180802a> and subsequent commits dealing with the websocket mocks.  They should have no bearing on this pull request.

**Pull request merged**
