### PR TITLE
156854856 generate key pair

### PR DESCRIPTION
**Pull request by easye**
q.v. <https://www.pivotaltracker.com/n/projects/2138843/stories/156854856>

### CODE REVIEW

**Review by guitarvydas — CHANGES_REQUESTED** [review]
This creates two emotiq/wallet defsystems.

I will take the code in this branch and create a new branch for 156854872 (correct?)

**Comment by easye** [comment]
@guitarvydas Removed the duplicated ASDF definition. 

It would be easier to get this merged into `dev` with your approval, then you can base your changes on `dev`.

**Comment by guitarvydas** [comment]
This builds under LWL, but Travis fails on 1/2 tests.  Is the first Travis build significant?

**Comment by easye** [comment]
@guitarvydas I have no idea what the first Travis build involves.  Sometimes it works, sometime it doesn't.  I haven't been able to discern a pattern to it.

**Comment by echupriyanov** [comment]
@easye I will look into that

**Comment by easye** [comment]
@guitarvydas I have changed the ASDF definition.  Please review again.

**Comment by guitarvydas** [comment]
[April 25] This is still failing on the first Travis build.  I was going to copy/paste some of the errors, but I'm getting a very inconsistent UI in github (2 PRs then 6, etc).  I don't understand 2 sets of errors, but a third set complains about QL missing.  [I was signed out of github overnight without any indication - maybe that resulted in the strange behaviour]

**Review by guitarvydas — APPROVED** [review]

**Pull request merged**
