### PR TITLE
Operational Cosi with BLS Signatures

### PR DESCRIPTION
**Pull request by dbmcclain**

### CODE REVIEW

**Comment by easye** [comment]
@markhdavid  Need to come up with a script for the CI which will run the `make` infrastructure for linux-amd64 with the stock Ubuntu Trusty64 Linux binutils/gcc/ldd toolchain.

**Comment by markhdavid** [comment]
@easye I don't really get what this all means:

> run the make infrastructure for linux-amd64 with the stock Ubuntu Trusty64 Linux binutils/gcc/ldd toolchain

I mean probably some of it but I'm not sure. So let's be sure. Can you break this down for me a bit, please?

**Comment by easye** [comment]
> On Mar 19, 2018, at 04:09, markhdavid <notifications@github.com> wrote:
> 
> @easye I don't really get what this all means:
> 
> run the make infrastructure for linux-amd64 with the stock Ubuntu Trusty64 Linux binutils/gcc/ldd toolchain
> 
> I mean probably some of it but I'm not sure. So let's be sure. Can you break this down for me a bit, please?
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 

We need code to automatically produce the native libraries under the CI.

Alternatively, we need to have a process that the Travis CI can invoke to download the native libraries.  This kind of depends on how often the native libraries change.  But we would still need a devops process to produce the native binaries under the ubuntu-trusty64-amd64 environment used for the Travis-CI.

It would be easiest to push the native binaries into S3 via the `emotiq` Quicklisp dist mechanism, as that is already available for the Travis CI process to `ql:quickload`.

**Comment by easye** [comment]
@guitarvydas Current needs for the native libraries summarized:

We need code to automatically produce the native libraries under the CI. Alternatively, we need to have a process that the Travis CI can invoke to download the native libraries. This kind of depends on how often the native libraries change. But we would still need a devops process to produce the native binaries under the ubuntu-trusty64-amd64 environment used for the Travis-CI. It would be easiest to push the native binaries into S3 via the `emotiq` Quicklisp dist mechanism, as that is already available for the Travis CI process to `ql:quickload`.

If @guitarvydas can push the needed Makefiles to this named branch, I will ensure that we can merge that to `dev`.

**Review by easye — CHANGES_REQUESTED** [review]
Need build recipe for native libraries for Ubuntu Trusty64

**Pull request closed without merging**
