### PR TITLE
Fix test network generation for multiple nodes on the same machine

### PR DESCRIPTION
**Pull request by easye**
Refactor the way we make configurations to simplify.

Split testing of network generation into separate test system that
depends on COSI-BLS and actually probes the filesystem to see that
directories are generated.

Fixes and tests <https://github.com/emotiq/emotiq/issues/307>.

### CODE REVIEW

**Comment by easye** [comment]
c.f. <https://github.com/emotiq/emotiq/issues/307>

**Review by echupriyanov — CHANGES_REQUESTED** [review]
In the generated `emotiq-conf.json` value of `gossipServerPort` is still 65002 regardless of provided values

**Comment by easye** [comment]
@echupriyanov 

> In the generated emotiq-conf.json value of gossipServerPort is still 65002 regardless of provided values

I don't observe that behavior.  Perhaps you are looking at older configuration files that haven't been rewritten?

```
(emotiq/config:network/generate :root #p"/var/tmp/foo/" :nodes-dns-ip '((:hostname "127.0.0.1" :ip "127.0.0.1" :gossip-server-port 65000 :rest-server-port 3140 :websocket-server-port 3145) (:hostname "127.0.0.1" :ip "127.0.0.1" :gossip-server-port 65001 :rest-server-port 3141 :websocket-server-port 3146) (:hostname "127.0.0.1" :ip "127.0.0.1" :gossip-server-port 65002 :rest-server-port 3142 :websocket-server-port 3147)))
```

```
grep -c 65001 /var/tmp/foo/127.0.0.1-127.0.0.1-65001-3141-3146/emotiq-conf.json 
1
```

Could you please recheck on your side?  Or give me more details about how this is failing for you?

**Comment by echupriyanov** [comment]
Cleared `~/.cache/common-lisp`, removed `/var/tmp/conf`, rerun `(emotiq/config:network/generate)`
Still no luck:
```
eric@peccopa ~/C/E/a/zerotier> cat /var/tmp/conf/127.0.0.1-127.0.0.1-65000-3140-3145/emotiq-conf.json |python -m json.tool
{
    "addressForCoins": 11672683214697130316969480737382011475585532747944610101615033862670914931782700310657572985879355964086589079498211618244868463890511743785948298676015296617968907548659339617027825358612000674174372844302515928876538675261769769476075566450456159382695604903641384694281472,
    "genesisBlockFile": "emotiq-genesis-block.json",
    "gossipServer": "true",
    "gossipServerPort": 65002,
    "hostname": "localhost",
    "ip": "127.0.0.1",
    "private": 1380261009581757190636103963884943693454758170599883441499847831066811260254857845178663185743232861054417974018061334821738428787180149,
    "public": 11672683214697130316969480737382011475585532747944610101615033862670914931782700310657572985879355964086589079498211618244868463890511743785948298676015296617968907548659339617027825358612000674174372844302515928876538675261769769476075566450456159382695604903641384694281472,
    "restServer": "true",
    "restServerPort": 3140,
    "stakes": [
        [
            11672683214697130316969480737382011475585532747944610101615033862670914931782700310657572985879355964086589079498211618244868463890511743785948298676015296617968907548659339617027825358612000674174372844302515928876538675261769769476075566450456159382695604903641384694281472,
            532177
        ],
        [
            36801617761589504320510887518779743625906184358812783992491192794032824402681237455505400912167057376960773283962511847118351602884917853103059535226504936208200283162628699666030131213889797199093230577003629197134887815534564283562401605900775988216709069558360323476665857,
            264772
        ],
        [
            23602349181835689704409148160267660529318937235775670997002096407571100514922260966002276961720888281607499399229486176321758224486118083721846117703000029352145289286828090272868486074669896321138376747980635612673076804277811457835159253594875416552022680898289628215017472,
            130317
        ]
    ],
    "websocketServer": "true",
    "websocketServerPort": 3145
}
eric@peccopa ~/C/E/a/zerotier> 
```

**Comment by easye** [comment]
@echupriyanov 

I will write some tests for this this for you to execute, as I cannot reproduce locally.

**Comment by easye** [comment]
@echupriyanov I did indeed find a bug in my approach.  Please review again when you have a chance.

**Comment by echupriyanov** [comment]
@easye Yes, `emotiq-config.json` is generated correctly now.

**Review by echupriyanov — APPROVED** [review]

**Comment by echupriyanov** [comment]
@easye Current `dev`, `dev-eu` and `dev-us` don't have this fixes applied.
I've updated this PR to work with current `dev`.

**Comment by easye** [comment]
I think all the changes have been incorporated via <https://github.com/emotiq/emotiq/pull/389> but I need to double-check.

**Comment by echupriyanov** [comment]
@easye this changes were never incorporated. thats what I'm talking about the whole last week.

**Comment by easye** [comment]
Fixed with #389

**Pull request closed without merging**
