### PR TITLE
Lg svs11pr

### PR DESCRIPTION
**Pull request by svspire**
Latest version; working and autonomously calling for elections on AWS nodes.

### CODE REVIEW

**Review by markhdavid — APPROVED** [review]
Runs for me. Compiles for me. I cannot do much more with this, other than approve it and move forward.

**Comment by markhdavid** [comment]
Looks like there's a rebase conflict with hash shake stuff.  That's a pain.  Ugh.
```

(defun get-hash-nbytes (nb &rest seeds)
  ;; returns a vector of nb raw-bytes
<<<<<<< HEAD
  (let ((dig (ironclad:make-digest :shake256 :output-length nb)))
    (dolist (seed seeds)
      (ironclad:update-digest dig (hashable seed)))
=======
  (let ((dig (ironclad:make-digest :shake128 :output-length nb)))
    (ironclad:update-digest dig (hashable seed))
>>>>>>> fixup GET-HASH-NBYTES to use SHAKE128 extendable output function.
    (ironclad:produce-digest dig)))
```

**Comment by svspire** [comment]
David and I have fixed this hash conflict half a dozen times but it just keeps coming back. The resolution is to keep the :shake256 clause and lose the :shake128 clause, but I have no idea how to make it stick.

**Review by easye — APPROVED** [review]
`emotiq/sim` continues to function.

**Pull request merged**
