### PR TITLE
Sim mte 20180619a

### PR DESCRIPTION
**Pull request by easye**

### CODE REVIEW

**Comment by markhdavid** [comment]
why are you adding commits while I'm reviewing this?

**Comment by easye** [comment]
@markhdavid The last four commits were added as part of the review that Paul and I did, for which you showed up on Meet. That was at least two hours ago.

**Comment by markhdavid** [comment]
Wasn't b04ff2b afterwards?  It appeared to come after I checked out the branch, which was after we met on meet.
-- it's OK - I've gotten the latest commits, but please avoid adding, or if you do, please let me know, since I do not plan to track this branch further.

**Comment by easye** [comment]
@markhdavid Paul and I continued to answer your outstanding comments on his previous commits.  We in b04ff2b we eliminated the use of internal symbol (aka "double colon" reference).

**Comment by easye** [comment]
Superseded by the (squashed) https://github.com/emotiq/emotiq/pull/236

**Pull request closed without merging**
