### PR TITLE
bitcoin-style base58-check p2pkh addresses

### PR DESCRIPTION
**Pull request by markhdavid**
bitcoin-style base58-check p2pkh addresses

- vec-repr:base58 method now left-pads with encoded 0's in vector case
- added base58 encoding unit tests (lifted from bitcoin's)
  test with: (asdf:test-system :crypto-pairings/t)
  notice: Base58-test
- added new hashes: hash/ripemd/160 and has/sha2/256
- added new module address.lisp which exports public-key-to-address
- created new unit tests file address-tests.lisp
  test with (asdf:test-system :cosi-bls-tests)
  notice: "Public Key to Key Hash as Address Test (Base58Check Encoding)"

### CODE REVIEW

**Comment by dbmcclain** [comment]
Two issues here...

1. What is the purpose of including SHA2/256? It is an outmoded hash function and current NIST recommendations are to avoid it in new code.

2. I see the prepending of zeros on BASE58, but I don't see any way to tell it how long the result should be, and when to use that padding.

Third issue, when I check out this branch, and perform:
(in-package :pbc)
(setf k (make-key-pair :dave))
(setf pkey (keying-triple-pkey k))
(base58 *) ;; --> goes into infinite loop

The correct result, from dev branch, is:

#<BASE58 8jUuBXBRfFD8edN6a6AVSiQ7cpgXdw9334hoKCuyF8euTM2vt8HaegspU9i7M8qfZGn6ob3Z1gsYFeK6bNfTmqHW25WXoyLfot5s78rzb755ARgg23KhSDBUBmwXP7tALUV2S28erhD9CyCLkg58gKD9kGrL >

**Comment by dbmcclain** [comment]
I think one source of confusion is that BASE58 is an integer encoding, not a vector encoding. An augmented form of BASE58 encoding could be defined so that it includes a vector length represented by the base58 encoding. But that would be a composite form. 

I actually had such a form at one time, and decided that neither HEX nor BASE58 were really vector encodings at all. 

And while you certainly can convert a vector form to base58 and hex strings, even with leading 0 bytes in the big endian representation, you might not get that same vector back if you convert to base58 then back again with BEV.  But a side function BEVN can be told how long the conversion should be, and does so with prepended zero bytes when the desired result is longer than the natural conversion back to vector form.

HEX actually could become a vector conversion directly, since it is based on power-of-two base. But BASE58 never could be. There is no grouping of bits in a vector that can give rise to base58 encoding. It is, and will always be, an integer encoding.

**Comment by markhdavid** [comment]
Answering the 2 issues:  

1. Use of sha2/256 is for the purpose of implementing this encoding. We are primarily doing it to be compatible with a convenient standard for addresses. This makes for convenient testing, allows for some interoperability with wallets, and will look professional and familiar to users of other cryptocurrencies, as has already been discussed.  Any deficiencies or concerns with sha2/256 on its own are dealth with by having the additional second hash (ripemd160), as was previously also discussed.

2. the length of the prepending is determined by the number of 0 bytes in at the beginning of the vector.

3. I don't know what's causing this issue. I'll track this down now. Thanks for bringing this to my attention.

**Comment by dbmcclain** [comment]
"the length of the prepending is determined by the number of 0 bytes in at the beginning of the vector."

Well, that can never be technically correct because 58 is not a power of 2.

**Comment by markhdavid** [comment]
Regarding integer encoding vs. vector encoding, we simply need a vector encoding.  There's no known use in our software for the integer encoding, nor for the decoding, but we have (and the world has) the vector encoding case very strongly, and it's being used about 2 million times a day for bitcoin address generation, so if you want, we can just use my simple function I wrote 2 days ago to generate it from a vector if you want to leave your code pure.  This is bumming me out.

**Comment by dbmcclain** [comment]
The issue revolves around the fact that 58 is not a power of 2. No grouping of bits can ever be used for convert from base58 representation to a vector, and vice versa. Hence conversion to integer form is always needed. So the next question becomes, is the vector to be big-endian, or little-endian?

**Comment by dbmcclain** [comment]
Honestly, I would have expected the function to generate addresses to require no more than a dozen lines of code, probably fewer.

**Comment by markhdavid** [comment]
I think there are about 20 odd lines of code in address.lisp. Let's not worry about that.  I'll take another shot at fixing the vec-repr.lisp stuff, unless you want to take over.

**Comment by dbmcclain** [comment]
I suggest that if you want a full-length conversion to base58, then be sure that the MSB of the integer equivalent of the vector be set to 1. Only then can you be sure to have a full-length base58 encoding. Perhaps that is what Bitcoin does?

**Comment by markhdavid** [comment]
I am sorry, I really did not see how it could possibly work to set the MSB of the integer to 1.    I do not know of anything like that done in Bitcoin code for doing base58 encoding.  Possibly I'm not following this well enough.

I fixed the bug I had introduced when I transformed the code in vec-repr: in the non-vector case, it needed to apply (INT X).  Should have just broken out a separate method based on arg type, so that's what I've done now. 

Also made testing a bit more verbose. (I've seen some cases where there is one failure indicated, but then it goes away. I'm not sure where the failure is, since verbose is off, other than it is somewhere in crypto tests. Kind of a "heisenbug".

**Comment by markhdavid** [comment]
The CI was stalled:

No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.

**Comment by dbmcclain** [comment]
I seem to recall that Bitcoin likes to use prefix bytes to indicate some sort of type. Those prefix bytes contain bits that are prepended to the key vector, ahead of conversion to base58. So setting the MSB is done in that manner.

**Comment by markhdavid** [comment]
Bitcoin’s mainnet P2PKH prefix is actually 0x00. 

Bitcoin’s test suite for encodings, which I’ve incorporated into unit tests I created, include a hex string starting “00...”, where its expected output begins “1...” — exactly the leading zero case.

**Comment by dbmcclain** [comment]
Okay, while I continue to disagree that the number of leading zero bytes in the vector has anything directly to do with the required number of padding chars on a base58 representation, the code is a credible performer, and I will go ahead and approve. The future will dictate whether this is a proper encoding system.

I just merged this branch with dev branch, and a typo correction in the networking layer, from my branch, and pushed back. 

This code continues to run the emotiq/sim tests properly for both uncloaked and cloaked transactions. It also properly withstands repeated (emotiq/sim::initialize).

Note that while leading zero bytes in a vector -> base58 get represented as "1", the inverse conversion produces a BEV without leading zero bytes. So the conversion is not directly reversible. But then it never was to begin with either.

**Review by dbmcclain — APPROVED** [review]

**Comment by dbmcclain** [comment]
I don't understand the Travis failures. But as far as I can tell, it has nothing to do with any of the code committed in this pull request. Looks like the failures were inherited from the merge with dev branch.

As for encodings, it all looks to me like "Paint-by-Numbers" programming - we do it this way because the other guys do it this way too. Nothing sensible justifies it. But oh well...

**Comment by markhdavid** [comment]
OH WOW, just noticed this: I had read where David wrote about approving and merging, and I'd assumed he'd merged it into dev and closed this, but I see he's been committing to this branch and merging it in with his branch.  I do not understand why this was done. I'll continue reviewing.

**Comment by markhdavid** [comment]
Although it was not the greatest procedure, in the interest of expediency I decided to let this go in via David's PR #184, which incorporates this PR. Accordingly, I'm closing this PR.

**Pull request closed without merging**
