### PR TITLE
Udp aws

### PR DESCRIPTION
**Pull request by svspire**
Supports UDP to/from AWS. Tested in LW and CCL.
(Because of NAT limitations, if one machine is behind NAT, it must be the client and AWS
must be the server. In other words, the machine behind NAT must solicit and AWS will reply.
AWS can solicit only to machines that are not behind a NAT firewall.)

### CODE REVIEW

**Comment by easye** [comment]
@svspire There is no reason to have developed an entirely new `http-request` mechanism when `drakma` provides a  acceptable, and battle-tested mechanism out-of-the box.

**Review by easye — CHANGES_REQUESTED** [review]
ASDF definition needs to `:depends-on` `quicklisp` as `http-fetch` uses code from that library.

**Comment by svspire** [comment]
> There is no reason to have developed an entirely new http-request mechanism when drakma provides a acceptable, and battle-tested mechanism out-of-the box.

There's a perfectly good reason, and here it is:
```
? (ql:quickload :drakma)
Systems loaded by QL: 
 ("puri" #P"/Users/svspire/quicklisp/dists/quicklisp/software/puri-20150923-git/")
 ("cl-base64" #P"/Users/svspire/quicklisp/dists/quicklisp/software/cl-base64-20150923-git/")
 ("trivial-gray-streams" #P"/Users/svspire/quicklisp/dists/quicklisp/software/trivial-gray-streams-20140826-git/")
 ("chunga" #P"/Users/svspire/quicklisp/dists/quicklisp/software/chunga-1.1.6/")
 ("flexi-streams" #P"/Users/svspire/quicklisp/dists/quicklisp/software/flexi-streams-1.0.15/")
 ("cl-ppcre" #P"/Users/svspire/quicklisp/dists/quicklisp/software/cl-ppcre-2.0.11/")
 ("chipz" #P"/Users/svspire/quicklisp/dists/quicklisp/software/chipz-20150505-git/")
 ("split-sequence" #P"/Users/svspire/quicklisp/dists/quicklisp/software/split-sequence-1.2/")
 ("usocket" #P"/Users/svspire/Lisp/third-party/usocket/")
 ("alexandria" #P"/Users/svspire/quicklisp/dists/quicklisp/software/alexandria-20150505-git/")
 ("trivial-features" #P"/Users/svspire/quicklisp/dists/quicklisp/software/trivial-features-20150923-git/")
 ("babel" #P"/Users/svspire/quicklisp/dists/quicklisp/software/babel-20150608-git/")
 ("cffi" #P"/Users/svspire/quicklisp/dists/quicklisp/software/cffi_0.16.1/")
 ("bordeaux-threads" #P"/Users/svspire/quicklisp/dists/quicklisp/software/bordeaux-threads-v0.8.4-git/")
 ("trivial-garbage" #P"/Users/svspire/quicklisp/dists/quicklisp/software/trivial-garbage-20150113-git/")
 ("cl+ssl" #P"/Users/svspire/Lisp/third-party/cl-plus-ssl/")
 ("drakma" #P"/Users/svspire/quicklisp/dists/quicklisp/software/drakma-2.0.2/")
```
Some of this we're already using, but most of it we're not, AFAIK. I have a very strong bias against bringing in seventeen levels of dependency on third-party libraries for things that can be written with one function.

That said, my function won't work on https so if we end up needing that, we'll have to use drakma. For now that's not necessary.

**Comment by svspire** [comment]
Furthermore, I didn't write http-fetch from scratch. It's a function that's already in Quicklisp, which we all already use. I just refactored it a bit for my purposes. If Quicklisp isn't battle-tested, I don't know what is.

**Comment by svspire** [comment]
> ASDF definition needs to :depends-on quicklisp as http-fetch uses code from that library.

Fixed.

**Review by easye — APPROVED** [review]

**Comment by easye** [comment]
@svspire 

I don't find your arguments against `drakma` persuasive:  we have an exact versioning of its dependencies that we can fix if necessary.  Almost all of the dependencies used by `drakma` are used in other places within `emotiq` at this point (like `usocket`), or should be (like `bordeaux-threads`), forming a standard part of the contemporary Common Lisp infrastructure. 

You have utilitized the Quicklisp client code with 100+ lines of additional code, depending on internals that are not in any way an official API. This is not really a "refactoring" in any sense of the word that I recognize it, but rather an aggregation of behavior upon the Quicklisp client code which is very hard to test.

**Pull request merged**
