### PR TITLE
Blocks mhd

### PR DESCRIPTION
**Pull request by markhdavid**

### CODE REVIEW

**Review by easye — CHANGES_REQUESTED** [review]
@markhdavid Need to remove inadvertent check-in of emacs backup file  `emotiq/src/tests/#blockchain-test.lisp#`

**Comment by markhdavid** [comment]
Review welcome, but do not merge please.  I may have a replacement or modifications soon.

**Comment by markhdavid** [comment]
Good catch @easye 
I removed the offending file. Also fixed something in unit tests. (Forgotten commit, actually.)
Tested with: (asdf:test-system :emotiq-test) then (emotiq-test:test-blockchain)

**Comment by markhdavid** [comment]
Mark, let me close this while David (et al) think about the version in Cosi-BLS, which is different and evolved from this in various ways. Thanks for the review.

**Pull request closed without merging**
