### PR TITLE
Dbm cosi async bls

### PR DESCRIPTION
**Pull request by dbmcclain**
Completed merge with dev into my dbm repo, then branch this dbm-cost-Async-BLS repo for merge back into dev. That was the easiest merger from dev into dbm ever!

### CODE REVIEW

**Review by markhdavid — CHANGES_REQUESTED** [review]
I was surprised (asdf:make :cosi) no longer builds, and there's no longer a :cosi system. I missed that memo. Is this the replacement? (asdf:make :cosi-bls)?

When I tried that, it errored out somewhere in "DLL hell", MacOS version. Here's the error version:

When trying to find the address of init_pairing: Could not register handle for external module :PBCLIB (file-name /usr/local/lib64/libLispPBCIntf.dylib):
 dlopen(/usr/local/lib64/libLispPBCIntf.dylib, 5): image not found.

Any idea what that's about?

I'd like either changes to make this work, or a better explanation of how I should be building so I do this doesn't happen.

**Comment by easye** [comment]
> On Mar 20, 2018, at 09:35, markhdavid <notifications@github.com> wrote:
> 
> @markhdavid requested changes on this pull request.
> 
> I was surprised (asdf:make :cosi) no longer builds, and there's no longer a :cosi system. I missed that memo. Is this the replacement? (asdf:make :cosi-bls)?
> 
> When I tried that, it errored out somewhere in "DLL hell", MacOS version. Here's the error version:
> 
> When trying to find the address of init_pairing: Could not register handle for external module :PBCLIB (file-name /usr/local/lib64/libLispPBCIntf.dylib):
> dlopen(/usr/local/lib64/libLispPBCIntf.dylib, 5): image not found.
> 
> Any idea what that's about?
> 
> I'd like either changes to make this work, or a better explanation of how I should be building so I do this doesn't happen.
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 

I thought we agreed that we would lead @dbmclain through the process of necessary changes to merge.  

We have to provide the necessary machinery to make the DLLs build, or alternatively, build them once, and push them into the `emotiq` Quicklisp distribution.

**Comment by dbmcclain** [comment]
Hi Mark,

Cosi was split into two branches to preserve the existing (old) version. The old Cosi became Cosi-Schnorr, and the new one is Cosi-BLS. I modified the asdf files, but perhaps I screwed that up?

- DM

**Comment by dbmcclain** [comment]
There are 3 libs (plus associated static, dynamic versions and soft-links) all installed into /usr/local/lib. These are libmp for GNU MP, libpbc for Ben Lynn’s PBC crypto pairings, and libLispPBCIntf for our Lisp-to-C glue layer.

My Mac shows the following libraries in /usr/local/lib

libLispPBCIntf.dylib
libpbc.1.dylib
libpbc.a
libpbc.dylib (soft link)
libpbc.a
libgmp.10.dylib
libgmp.a
libgmp.dylib (soft link)
libgmp.la

- DM

**Comment by easye** [comment]
@dbmcclain Currently we are working on the native library integration under  https://github.com/emotiq/emotiq/pull/40

But maybe we should close this pull request in favor of using the version that you ported to `cffi` in https://github.com/emotiq/emotiq/pull/42?

**Pull request merged**
