### PR TITLE
15692472 production bash

### PR DESCRIPTION
**Pull request by guitarvydas**
- pass cmd line args through emotiq.bash to binary (emotiq) - debug (in startup.lisp) prints the args
- production.bash calls build-crypto-pairings.bash
- arch .macos, all scripts renamed with this suffix (i.e. .osx --> .macos)
- version (date) for binary
- binary tar'ed into a directory
(supersedes PR 103)

### CODE REVIEW

**Comment by echupriyanov** [comment]
Branched from here to `156925103-build-and-upload-binary-distribution` for building binaries in Travis

**Comment by easye** [comment]
@guitarvydas Still failing for me under macos

Running `production.bash` fails:

```
tar: emtq-20180427180839-macos/emotiq: Cannot stat: No such file or directory
tar: emtq-20180427180839-macos/libLispPBCIntf.dylib: Cannot stat: No such file or directory
tar: Error exit delayed from previous errors.
+ rm -rf /Users/evenson/work/emotiq/etc/../var/local/production/emtq-20180427180839-macos
```

**Comment by echupriyanov** [comment]
Already fixed that in my branch.

**Comment by easye** [comment]
@echupriyanov, @guitarvydas  So, should we close this pull request as not relevant?

**Comment by echupriyanov** [comment]
I was planning to have full CI pipeline with release before merge. Though, probably this PR can be closed.

**Pull request closed without merging**
